version: '3.3'

services:
  telebard:
    image: bard_telegram_bot
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-telegramtoken}
      - _BARD_API_KEY=${_BARD_API_KEY:-bardkey}
    restart: unless-stopped 
      
