version: '3.3'

services:
  app:
    image: bard_bot
    ports:
      - 8080:8080
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-telegramtoken}
      - _BARD_API_KEY=${_BARD_API_KEY:-bardkey}
    restart: unless-stopped 
      
